#ifndef APEX_FACTOR_READER_H
#define APEX_FACTOR_READER_H

#include <string>
#include <map>
#include <vector>
#include <memory>
#include <fstream>
#include <string>
#include <iostream>
#include <regex>
#include <optional>
#include "reader_util.h"
#include <boost/iostreams/filtering_streambuf.hpp>
#include <boost/iostreams/filter/gzip.hpp>

/**
 * Class to read factors generated by apex factor.
 */
class FactorReader {
protected:
  std::vector<std::vector<double>> rows;
  std::vector<std::string> samples; // sample names (columns)
  std::vector<std::string> covariates; // covariate names (rows)
public:
  FactorReader(const std::string &file);
  void load(const std::string &file);

  bool operator==(const FactorReader& other);
};

#endif //APEX_FACTOR_READER_H